default: default
variants:
  - name: Another Default
    template: default.lynx.yml
    data: default.data.yml
  - name: Other
    template: other.lynx.yml
    data: default.data.yml
  - name: Invalid Form
    template: ../default.data.yml
    data: default.data.yml
