spec:
  hints~: [ card, section ]
  visibility~: hidden
  # emphasis~:
  # validation~:
  #   required~:
  #     invalid~?requiredMessage: requiredMessage
  #   text:
  #     minLength~?minLength:
  #       invalid: minLengthMessage
  # options~?options: options
value:
  header: Header
  ~*:
  footer: Footer
